title:i      "Himpunan Peraturan NKRI 2021"
version:     "0011--25-Jul-2021"
copyright:   "2021-2021"
description: Himpunan Peraturan NKRI 2021.
      This site is managed by VauLSMorg (vlsm.org) since 2021.
google_analytics: UA-89852122-7
disc: You are free to share, copy and redistribute the material of this site 
      in any medium or format for any purpose, even commercially. 
      Please give appropriate credit, provide a link to the page, 
      and indicate if changes were made. You may do so in any reasonable manner. 
      You should not apply legal terms or technological measures, 
      that legally restrict others from doing anything that is permited here.
author: Cicak Bin Kadal
show_downloads: false
theme: jekyll-theme-hacker
sitemap: true
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
social:
  name: URLs
  links:
    - https://https://github.com/rms46/uuri
# github:
#    zip_url: https://github.com/...
#    tar_url: https://github.com/...
github: [metadata]

author:           "Abu Akbar Al-Kulunia"
address:          "Schiller Str., Cologne 50859"
sitemap:          "true"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
urlweb:           "https://uuppri.github.io/2021/"
urlcontact:       "TBA"
urlgithub:        "https://github.com/UUPPRI/2021/"
urlghpage:        "https://uuppri.github.io/2021/"
keywords:         "jekyll, testing"
github:           [metadata]

